### ISSUE TITLE
Merge the plotting functionalities in RGDR module

### ISSUE THREAD

**Issue by geek-yang** [AI4S2S/s2spy#102]
Currently in RGDR module, there are two ways to plot the clusters:
- Preview the clusters by `RGDR(...).plot_clusters(precursor_field, target_timeseries)`
- Plotting clusters after fitting and transforming `cluster_map.cluster_labels[0].plot()`

The first option was designed to let the user have a quick check and preview the clusters. But it can cause confusion. We can merge these two functionalities and ask the user to `fit/transform` first and then `plot` the clusters.

**Comment by Peter9192** [comment]
Just to add to this: I think the confusion is caused mainly by the fact that `.plot_clusters(...)` takes the same arguments as `fit()`, so it seems to the user to do exactly the same thing as `fit(...).cluster_labels[0].plot()`. Since the latter also stores the result, it is probably more convenient to work with anyway, and it makes sense to keep only this one.

**Comment by BSchilperoort** [comment]
For completion's sake: the method called after fitting & transforming (`cluster_map.cluster_labels[0].plot()`) is an xarray built-in plot method.

The two methods `plot_clusters` and `plot_correlation` were more meant as utility plots without needing to go through fitting & transforming _all_ the data. These being renamed to `preview_clusters` and `preview_correlation` would more clearly signal their intended use.

Compare the two options below. Keep in mind that the users likely wants to tune the RGDR configuration, and only perform the calculation for a single lag to reduce computational time (which becomes quite significant with higher resolution data).

<hr>

Current functionality ("preview mode")

```py
RGDR(eps=400).preview_clusters(precursor, target, lag=1)
RGDR(eps=800).preview_clusters(precursor, target, lag=1)
```

<hr>
Without preview:

```py
_precursor = precursor.sel(i_interval=1)  # Select the lag to plot

for eps in (400, 800):
    rgdr = RGDR(eps=eps).fit(_precursor , target)
    clustered_data = rgdr.transform(precursor_field)
    clustered_data.cluster_labels[0].plot()
```

**Comment by geek-yang** [comment]
Thanks for your consideration @BSchilperoort. Based on the feedback from @jannesvaningen during the sprint day, now I'm a bit hesitant about, whether we should remove the preview method or not. Indeed it helps the user in an interactive way. 

Now I'm thinking, maybe we can add more explanation in the tutorial notebook and explain this to the user, why these methods are there and stress the big advantage of preview provided a super large dataset. And as what you suggested, we can also rename the method to `preview_xxxx` to make it more explicit and therefore avoid confusion.
