### ISSUE TITLE
Change to `allow_overlap`/`skip_n_years` in calendars (CustomCalendar)

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/s2spy#112]
I had the idea to make `allow_overlap=False` work differently internally. Why don't we first generate the intervals, and then throw out anchor years if there is overlap. This avoids having to do complex calculations when working with non-day Timedeltas.
For the plotting utilities we already require a `get_overlapping_periods` method on the calendar anyway (to display which intervals overlap).

Some pseudocode:

```py
intervals = self.get_intervals()
overlap, overlapping_intervals = assert_overlap(intervals)
while overlap:
    self.skip_years = 1
    intervals = self.get_intervals()
    overlap, _ = assert_overlap(intervals)
```

Of course this makes generating the calendar a bit slower, but I don't think the calendar generation will ever be a bottleneck. On the upside; it makes our code a lot simpler.

**Comment by Peter9192** [comment]
What about

```py
intervals = self.get_intervals()
self.skip_years = discard_overlap(intervals, tolerance=5)
```
