### ISSUE TITLE
Design preprocessing module

### ISSUE THREAD

**Issue by geek-yang** [AI4S2S/s2spy#115]
Next step, we need to design a preprocessing module and insert it into our current workflow. It is better that we start thinking about it now and try to make some room as currently some low level changes are being made to the existing modules.

There are several functionalities we would like to include in our package:
- Detrend
- Remove seasonality
- Take anomalies
- Take running mean

These operations are not difficult if they are performed per anchor year. But for the whole timeseries, we need to think about how to address them within the current workflow. We can have some brainstorming here.

**Comment by Peter9192** [comment]
I would say: start with an example usecase/notebook/script that does each of these steps without s2spy. That will make sure that the requirements are clear.

**Comment by BSchilperoort** [comment]
The basic preprocessing module has been implemented.
