### ISSUE TITLE
Pinning `mypy` version

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/s2spy#134]
We use `mypy` to check our static types. However, as mypy is still in a 0.x version, the functionality can with new releases, and raise errors in the CI that have nothing to do with changes made by a certain commit.

It is not fun or helpful to see the ❌ show up because of mypy version changes. I'd suggest to pin the mypy version, and periodically update it to avoid this kind of problem.

Example: [0.991 (latest) contains two breaking changes](https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html)

**Comment by geek-yang** [comment]
That sounds good and reasonable to me. Let's fix the version.
