### ISSUE TITLE
Split off Calendar module

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/s2spy#154]
We discussed the idea to split off the calendar module from s2spy, as it could work well as a standalone package and in that capacity can be generalized to serve a much broader audience. A potential downside of this could be that changes to the calendar would require a refactor of dependent code in s2spy, and keeping them in sync.

I started brainstorming about a fitting package name. So far I've come up with (think `from ... import Calendar, resample`):

- chronology (the science of measurement of time)
- chronometry (the study of ordering of events)
- chrononomy (a combi of the above)
- chronolopy (a python suffix to the above)
- horology (the study of measuring time but mostly used for short time as in watches)
- menology (study of months but more widely used as an ecclectical calendar of saints or martyrs)
- calendarian (maker of calendars)
- lunisolar (a type of calendar)
- mesopotamia (origin of the first known calendars)
- gregory or pope-gregory (the godfather of the Gregorian calendar)
- gridcal (as in: a calendar in a grid)
- timetable (referring to the 2d nature of our calendars)
- intercal (from intercalation, the act of adding leap intervals to sync with the heavens)
- annals (historical records ordered chronologically)
- hanke-henry (a proposal for calendar reform)
- chulasakarat (Asian calendar, cool name but perhaps controversial?)
- tzolkin (Mayan calendar, meaning 'division of days')
- yold (Year of Our Lady of Discord, the "BC" of the discordian calendar, discordia is the goddess of chaos in Discordianism)

Not all are immediately fit for purpose,but perhaps they inspire other ideas. What do you think?

**Comment by Peter9192** [comment]
@BSchilperoort Want to update this thread with our final decision?

**Comment by BSchilperoort** [comment]
We have decided on [`lilio`](https://github.com/AI4S2S/lilio), named after [the inventor of the Gregorian calendar](https://en.wikipedia.org/wiki/Aloysius_Lilius).

It's a short name, available on PyPI, has no other meaning elsewhere, and is closely related to our calendar system.

We also liked
```py
from lilio import Calendar
```
more than
```py
from calendarian import Calendar
```
