### ISSUE TITLE
How to deal with doctest formatting issues? (Consider adding pytest-accept)

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/s2spy#29]
In this repo we are using doctest to check whether the examples in the documentation still produce the expected output. But sometimes we make small modifications and the output is supposed to change. In that case, we need to update the expected outputs.

One option is to run the example code in your own IDE, and copy it to the docstrings. Another option is to copy the output of the test. However, in both cases, we run into small formatting errors e.g. related to trailing whitespace.

One option could be to consider [pytest-accept](https://github.com/max-sixty/pytest-accept). Or, we can look into whether we can configure the tests to ignore whitespace issues.

**Comment by BSchilperoort** [comment]
Apparently doctest has a flag which allows for normalizing whitespaces. See;
https://stackoverflow.com/questions/42372351/how-to-insert-trailing-spaces-in-a-doctest-so-that-it-doesnt-fail-even-when-ac
https://docs.python.org/3/library/doctest.html#doctest.NORMALIZE_WHITESPACE

**Comment by Peter9192** [comment]
Please bear in mind [this answer on SO](https://stackoverflow.com/a/9810040) that advises against doing this. But I think we have a valid usecase, as long as we manually verify that the updated test output indeed corresponds to what we would expect.

**Comment by geek-yang** [comment]
A quick note about the solution using `# doctest: +NORMALIZE_WHITESPACE`. The `doctest` used in ci/cd is provided by `sphinx`. It can pass the test (locally, called via `make doctest`) with `# doctest: +NORMALIZE_WHITESPACE` and it will not show up in the doc. However, since it still looks quite ugly in the code...Let's look for something elegant first.
