### ISSUE TITLE
Unintuitive behavior when passing weekly frequencies to calendar.

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/s2spy#33]
When passing a pandas frequency to the AdventCalendar such as '2W', Pandas uses calendar weeks to generate the intervals. This causes the situation where the anchor date is not always in an interval.

Example below:
```python
import s2s.time
calendar = s2s.time.AdventCalendar(anchor_date=(5, 10), freq='20W')
calendar.map_years(2019, 2020)
```
returns;
```
>>> i_interval                          0                         1
>>> anchor_year                                                    
>>> 2020         (2019-12-22, 2020-05-10]  (2019-08-04, 2019-12-22]
>>> 2019         (2018-12-16, 2019-05-05]  (2018-07-29, 2018-12-16]
```

Expected behavior: raise an error when frequencies such as calendar week are passed.

**Comment by BSchilperoort** [comment]
Additionally, what is the reason for allowing users to pass a pandas frequency, do we want to support any [other of the aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases)?

In my view it might be best to change `freq` so that in the case of the advent calendar users can only pass a number of days. Especially as weekly or monthly calendars would be a different class.

**Comment by Peter9192** [comment]
> Additionally, what is the reason for allowing users to pass a pandas frequency,

I wanted to stick with something that was already standardized and avoid having to reimplement our own frequency string parser. 

But indeed, seeing this behaviour: perhaps we should forbid anything that's not days
