### ISSUE TITLE
Linter configuration not consistent between linters

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/s2spy#35]
In the repository some linter configurations are in the `setup.cfg` file (at least for isort), but specific linter problems are silenced in `.prospector.yml` as well.

It is desirable that linters on everyone's machines agree on which python style guides to follow, or that we agree to use a specific linter.

Note that Github Actions is configured to use prospector and isort for the linting check.

Related to #13

**Comment by geek-yang** [comment]
We use `ruff` now. This issue can be closed.
