### ISSUE TITLE
Supporting multiple target intervals in `map_correlation`.

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/s2spy#56]
Currently `rgdr`'s `map_correlation` implementation will calculate the correlation coefficient and p-value between precursor data and target data. It will calculate this over the `anchor_year` dim,  for every dimension in the input data (e.g. `latitude`, `longitude`, `i_interval`). 

However, it does not take into account the Calendar's `n_targets`, more specifically the case where multiple intervals are labelled as target. 
A wrapper function is required to handle this. In the case of multiple target intervals, the precursor data and field data for those intervals are flattened over the `i_interval` dimension. 

The following image serves as a visualization for this concept:
[![image](https://user-images.githubusercontent.com/12114825/181215172-86c33687-51a9-479f-9a54-aa5d556d0bc4.png)](https://nlesc.sharepoint.com/:p:/s/team-beta/EZHgy9Agmd5EieXKWuAUhLgB2eCOxRZaIRfDuStLq8b23w?e=53nCDX)

**Comment by Peter9192** [comment]
By multiple target periods you mean "a target period consisting of multiple data points/intervals", right?

**Comment by BSchilperoort** [comment]
> a target period consisting of multiple data points/intervals

Yes, exactly. I'll clarify this in the issue
