### ISSUE TITLE
Directly pushing commits to `main`

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/s2spy#59]
Yesterday I accidentally pushed a commit intended for a different branch to `main`. Would we want to make this so that we as administrators cannot do this, as a precautionary measure?

**Comment by Peter9192** [comment]
Or should we revoke your admin rights? 😛 

From my experience, I don't recall this ever happening, but I do recall having had a use case where it was useful that I could push directly to main. That was a quick, time-critical bugfix, and you could argue that such things shouldn't happen either. 

In conclusion, I'm a bit ambivalent.

**Comment by BSchilperoort** [comment]
Ok! I guess reverting is always possible in case of a screw-up.
I was mostly surprised that I was not even asked to confirm the push to main.

Apparently I can prevent myself from repeating this mistake by setting my push remote to some invalid value on the main branch
`git config branch.main.pushremote no_push`

**Comment by Peter9192** [comment]
I just updated the branch protection rule to also apply to admins.
