### ISSUE TITLE
NWP Calendar type

### ISSUE THREAD

**Issue by semvijverberg** [AI4S2S/s2spy#78]
Related to #30: 
Making a comparison with NWP predictions is not always trivial, especially not in the following scenario:

Numerical Weather Predictions (NWP) are often released at regular time-intervals. For example, we have an EC46 forecast, which is initialized every Thursday of the week. If the goal is to predict 30-day mean periods with 2-weeks lead-time, we can analyse the skill of each forecast initialization. Imagine, we would like to verify the skill of such forecast within a target period (e.g. OND), then we can analyse the forecast ~12 times (as there are roughly 12 weeks in that period). If we would like to compare this NWP forecast with a data-driven forecast, we must be able to let the data-driven forecast perform the same task. We could iterate and train a separate forecast model for each 30-day mean period within the verification period (OND) with a gap lead-time of 2 weeks. But assuming the dynamics are approx. stable throughout the verification period (OND), we could also train a single model over all 30-day mean periods at once. <- it would be nice if we could create a calendar which can do this. Difficulty may be with finding the an easy set of parameters. 

*just to get started with an example:
`calendar = s2spy.time.NWPCalendar(day_of_week='thursday', months_as_ints=[10,11,12], lead_time='14d', target_aggregation='30d', precursor_aggregation='30d')`

![image](https://user-images.githubusercontent.com/35559713/184611885-e042a53d-9b6c-450f-a5ea-48332c6f9a15.png)

**Comment by semvijverberg** [comment]
Perhaps it could be a minor adaptation from the existing AdventCalendar, where you allow for a percentage of overlap?  For example, in the ensemble is released every 7 days, i.e., each 30 day-mean target period has 7/30~23% overlap.

**Comment by Peter9192** [comment]
Interesting! Intuitively I think the first approach you suggest is the fairest comparison, and I would consider the second approach a "feature". If I understand you correctly, it can be summarized alternatively as "a calendar with overlapping (target) intervals/periods". Correct?

**Comment by Peter9192** [comment]
Nice illustration by the way, I really like that we found a good way to illustrate what we're talking about

**Comment by Peter9192** [comment]
> calendar = s2spy.time.NWPCalendar(day_of_week='thursday', months_as_ints=[10,11,12], lead_time='14d', target_aggregation='30d', precursor_aggregation='30d')

This suggestion incorporates several new features: 

- It assumes we'll have a "lead-time" specification as an alternative to a lag time (#47)
- It allows specifying the target period as a list of month numbers
- It adds a "forecast issue date"
- It looks like you'd be able to specify a different frequency for target and precursor. That would be another feature, which can be discussed separately. 

All these are indeed relevant features but perhaps we should focus on one of them at a time. Shall we keep this issue open as a great example use case and for high-level discussion, and open separate issues for the individual features?

**Comment by BSchilperoort** [comment]
> then we can analyse the forecast ~12 times (as there are roughly 12 weeks in that period)

Another new feature: it seems to me like this describes an `anchor_week` instead of `anchor_year`.

@semvijverberg would this NWPCalendar only be for a single year?

**Comment by semvijverberg** [comment]
This NWPCalendar is repeated throughout each year and is basically an AdventCalendar with overlapping intervals, but I started out with all these parameters
`calendar = s2spy.time.NWPCalendar(day_of_week='thursday', months_as_ints=[10,11,12], lead_time='14d', target_aggregation='30d', precursor_aggregation='30d')` 
as they are more intuitive from a user-perspective.

**Comment by semvijverberg** [comment]
@Peter9192 I agree we can split this issue. 
For example, 
1. the lag_gap feature is basically already close to a NWP perspective, where you have an initialization time and lead_time. 
2. Specifying the precursor and target aggregation can also be useful for a wider range of use cases
3. This completely new issue, related to overlapping intervals.

**Comment by geek-yang** [comment]
Just got this in a different way...For this NWP use case, what we try to solve is just a sliding window problem. We just need to define the intervals once and do a loop to move forward...Why do we need a calendar for this? By creating a calendar like what @semvijverberg showed in the figure will cause lots of overlapping of data...The only advantage I could see is, this way we can parallel the computation, but with more space to store data as a trade off...

I think we can support a workflow to do this based on a sliding window, and define intervals sort of describing the calendar in the figure.
